### ISSUE TITLE
Build errors (Cannot find module '/out/src/browser.js' )

### ISSUE THREAD

**Issue by senpl** [FabianLauer/chrome-vs-code#18]
steps to reproduce
clone repo
yarn install
I get that error(build docs would also be nice):
cp -r src/static/ out/src/static
./node_modules/.bin/coffee ./scripts/compileLessCss.coffee
./node_modules/.bin/browserify ./out/src/browser.js > ./out/src/browser.all.js
Error: Cannot find module '/home/m/chrome-vs-code/out/src/browser.js' from '/home/m/chrome-vs-code'
    at /home/m/chrome-vs-code/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/home/m/chrome-vs-code/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/m/chrome-vs-code/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/m/chrome-vs-code/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:166:21)
Makefile:7: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by FabianLauer** [comment]
OK, no idea if yarn will work here (it should, I know, I know). You could try `npm install` instead.

**Comment by senpl** [comment]
`npm install` not worked for me too, but with less clear error output. This is why I like simple instruction how it is build, at least on creator machine (because other could know when they do something not as expected).
